apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: sacrificial
  namespace: kubesentinel
  labels:
    app: sacrificial
    app.kubernetes.io/name: sacrificial
    # This label must match the Helm values.yaml serviceMonitorSelector
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: sacrificial
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
      scrapeTimeout: 10s
